### ISSUE TITLE
Compile issue GCC4.8.5

### ISSUE THREAD

**Issue by Tongdongq** [OPM/opm-common#799]
I'm working on an old server, that I don't have sudo rights to.
My local repo is on the release/2019.04 branch, commit 8fa165c0 (May 8 2019).
I tried the standard `mkdir build && cd build && cmake .. && make` route, but I get an error:

```
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:42,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from /data/work/tqiu/opm/opm-common/opm/parser/eclipse/Deck/Deck.hpp:29,
                 from /data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/Grid/GridDims.hpp:27,
                 from /data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp:28,
                 from /data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/Aquancon.hpp:29,
                 from /data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/Aquancon.cpp:20:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::pair_elements*, std::vector<Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::pair_elements> >; _Tp = Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::pair_elements; _Compare = Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::__lambda0]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::pair_elements*, std::vector<Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::pair_elements> >; _Compare = Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::__lambda0]’
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::pair_elements*, std::vector<Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::pair_elements> >; _Size = long int; _Compare = Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::__lambda0]’
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::pair_elements*, std::vector<Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::pair_elements> >; _Compare = Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::__lambda0]’
/data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/Aquancon.cpp:209:22:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: no match for call to ‘(Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::__lambda0) (Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::pair_elements&, const Opm::Aquancon::logic_application(const std::vector<Opm::Aquancon::AquanconOutput>&)::pair_elements&)’
    while (__comp(*__first, __pivot))
...
```
The error(s) also mention `opm/prerequisites/install/include/ert/ecl/ecl_util.hpp`, this seems to be a libecl file, I took the 2.4.1 release, so it should be stable.
I had trouble installing GraphBLAS and Mongoose from SuiteSparse so left them out, but I think only UMFPACK is needed.

Info on system:
GCC 4.8.5 (so no c++14)
Boost 1.53 (I have 1.70 locally)
CentOS 7

**Comment by alfbr** [comment]
Unfortuantely compiling with GCC 4.8 broke some time ago. Today, you need at least GCC 4.9. Red Hat provides access to newer GCC versions in the developer toolsets. Hence, on the node you compile, you currently need access to at least one version of the developer toolsets from Red Hat. The resulting binaries will work on any Red Hat 7 node.

**Comment by Tongdongq** [comment]
Thanks for your quick reply!
Do you happen to know which release is compatible with GCC 4.8?

**Comment by alfbr** [comment]
Sorry, I don't know. I accidentally discovered it sometime this year. Chances are you will be able to compile any version from 2018. We did tag one version just before Christmas, so you can checkout that one, and see if it compiles with 4.8.

**Comment by Tongdongq** [comment]
Branch release/2018.10 also fails:
```
In file included from /data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp:37:0:
/data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp:39:38: error: expected ‘)’ before ‘*’ token
         SummaryNode(smspec_node_type * c_ptr) :
                                      ^
/data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp:47:15: error: ‘smspec_node_type’ does not name a type
         const smspec_node_type * get() const {
               ^
/data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp:76:9: error: ‘smspec_node_type’ does not name a type
         smspec_node_type * ptr;
         ^
/data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp: In copy constructor ‘Opm::SummaryNode::SummaryNode(const Opm::SummaryNode&)’:
/data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp:44:13: error: class ‘Opm::SummaryNode’ does not have any field named ‘ptr’
             ptr( smspec_node_alloc_copy(other.get()))
             ^
/data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp:44:47: error: ‘const class Opm::SummaryNode’ has no member named ‘get’
             ptr( smspec_node_alloc_copy(other.get()))
                                               ^
/data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp: In member function ‘std::string Opm::SummaryNode::wgname() const’:
/data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp:52:49: error: ‘const class Opm::SummaryNode’ has no member named ‘ptr’
             return smspec_node_get_wgname(this->ptr);
...
/data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp: In function ‘void Opm::{anonymous}::keywordW(Opm::SummaryConfig::keyword_list&, const Opm::ParseContext&, const Opm::DeckKeyword&, const Opm::Schedule&)’:
/data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp:167:86: error: invalid conversion from ‘const char*’ to ‘int’ [-fpermissive]
                                                                                 0,0,0)));
                                                                                      ^
/data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp:167:86: error: too many arguments to function ‘void* smspec_node_alloc(int, const char*, const char*, int, const char*, const int*, float, const char*)’
In file included from /data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp:27:0,
                 from /data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp:37:
/data/work/tqiu/opm/prerequisites/install/include/ert/ecl/smspec_node.h:79:10: note: declared here
   void * smspec_node_alloc( int param_index,
          ^
/data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp:167:87: error: no matching function for call to ‘Opm::SummaryNode::SummaryNode(void*)’
                                                                                 0,0,0)));
                                                                                       ^
/data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp:167:87: note: candidate is:
In file included from /data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp:37:0:
/data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp:43:9: note: Opm::SummaryNode::SummaryNode(const Opm::SummaryNode&)
         SummaryNode(const SummaryNode& other) :
         ^
/data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp:43:9: note:   no known conversion for argument 1 from ‘void*’ to ‘const Opm::SummaryNode&’
/data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp:177:82: error: invalid conversion from ‘const char*’ to ‘int’ [-fpermissive]
                                                                             0,0,0)));

...
```

**Comment by alfbr** [comment]
Well, then I suggest to just bite the bullet and install a developer toolset. Just checked, and they are available for CentOS too, look here:
http://mirror.centos.org/centos/7/sclo/x86_64/rh/devtoolset-7/
Recall that you only need it for compilation, the binaries will run without it.

**Comment by Tongdongq** [comment]
release/2018.04 also fails:
```
/data/work/tqiu/opm/opm-common/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp:39:30: fatal error: ert/ecl/Smspec.hpp: No such file or directory
 #include <ert/ecl/Smspec.hpp>
```
Changing the include to <ert/ecl/smspec_node.hpp>, like in newer version, also fails:
```
/data/work/tqiu/opm/opm-common/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp:42:34: error: ‘smspec_node’ is not a member of ‘ERT’
             typedef std::vector< ERT::smspec_node >::const_iterator const_iterator;
```
I'll try the devtools!

**Comment by bska** [comment]
> Branch release/2018.10 also fails:

Are you using a recent version of LibECL or a version corresponding to OPM's 2018.10 release?  The diagnostics for your 2018.10 build do at least **suggest** that you're trying to build an older version of OPM while targeting a newer version of LibECL.  As for your [original build failure](https://github.com/OPM/opm-common/issues/799#issue-452925800), I do recall seeing something similar a long time ago, but I've been using GCC 4.9.x for long enough&mdash;albeit lately with a local patch to opm-material due to incomplete/insufficient `constexpr` support in GCC 4.9&mdash;that I can't remember the details.

Looking at the [code in question](https://github.com/OPM/opm-common/blob/dff91dd742df97c20e2159e362a61f162d15d4d4/src/opm/parser/eclipse/EclipseState/Aquancon.cpp#L198-L209) I'm going to guess that the build failure is caused by passing a lambda defined in terms of local class [`pair_elements`](https://github.com/OPM/opm-common/blob/dff91dd742df97c20e2159e362a61f162d15d4d4/src/opm/parser/eclipse/EclipseState/Aquancon.cpp#L172-L179) to the standard library function `std::sort()`.  This is valid C++11 (and later), but it's also possible that GCC 4.8.x or its standard library does not support this usage.

At this point your options appear to be somewhat limited.  You can

  1. Use prebuilt packages from OPM's [website](https://opm-project.org/?page_id=245) although I don't really know if the RedHat Enterprise Linux packages can run on CentOS.

  2. Stick to an older OPM release once you're able to build it.  Do remember to match the LibECL version with that of OPM.

  3. Install the Developer Toolset as suggested by @alfbr .

The third option is probably the only viable solution long term, because we (the OPM project) are currently discussing raising the minimum compiler requirement to GCC 5 (corresponding to Ubuntu 16.04 LTS) or something more recent.  It is likely that being able to build OPM using GCC 4.8.x will become increasingly difficult and doing so will probably not be supported by the OPM project.

**Comment by alfbr** [comment]
> I don't really know if the RedHat Enterprise Linux packages can run on CentOS.

They install and run fine on CentOS.

> Install the Developer Toolset as suggested by @alfbr .

Yes, that is what I did. Please note that it suffices to give the absolute path to gcc/g++ in the cmake compiler variables in order for the build to use the devtoolset versions. Just ask if you need help.

**Comment by Tongdongq** [comment]
I did not realise the server already has devtoolset-7. I compiled with GCC 7.3.1 and ran SPE1 successfully, thanks!
